Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |docker|

    docker.image = "centos7-ssh" 
    docker.ports = ["2222:22"]
    
    docker.remains_running = true
  end

  config.ssh.username = "root"
  config.ssh.password = "rootpassword"
  config.ssh.port = 2222
end
